### ISSUE TITLE
I get the following error when trying to use the toWar.js

### ISSUE THREAD

**Issue by vanbac912** [juvian/wc3-translate#3]
I get the following error when trying to use the toWar.js . command
pjass not installed, can't validate script. Install from https://www.hiveworkshop.com/threads/pjass-updates.258738/

How should I solve it?
Thankss

**Comment by juvian** [comment]
Hi, that's just a warning, it should work even without it. But to prevent the warning you need to place pjass.exe in the same folder as toWar.js
