### ISSUE TITLE
Some problems with script translation

### ISSUE THREAD

**Issue by Surgeol** [juvian/wc3-translate#6]
Here are some examples
> <details> <summary>Original code</summary>
> 
> ![example1](https://user-images.githubusercontent.com/35412032/236124768-7e2961a7-ed39-4fb6-9381-5b04901860c6.png)
> </details>
> <details> <summary>Output</summary>
> 
> ![example2](https://user-images.githubusercontent.com/35412032/236124771-d4c5fd02-6e87-41ea-af8f-fb97f151709d.png)
> </details>
> 
> <details> <summary>Correct format should be like this</summary>
> 
> ![example3](https://user-images.githubusercontent.com/35412032/236126078-bc8c88c8-8f3c-48c5-ab63-38eef70a547a.png)
> </details>

Also, I don't get any translated strings from old file, all the strings are treated as new. you might need those files for a look.

> [old.zip](https://github.com/juvian/wc3-translate/files/11394230/old.zip)(translated to chinese)
> [new.zip](https://github.com/juvian/wc3-translate/files/11394229/new.zip)(still english)

**Comment by juvian** [comment]
I don't understand the issue, Original code shows no cffff things so output shows the same strings correctly. The correct format you show is not the same example as the other images. As for the translated strings from old file, which commands are you running? What is the output?

**Comment by Surgeol** [comment]
> I don't understand the issue, Original code shows no cffff things so output shows the same strings correctly. The correct format you show is not the same example as the other images. 

Sorry, I didn't describe the problem correctly. What I mean is that some output results are missing single quotes.
<details> <summary>This is a clearer example</summary>

![example4](https://user-images.githubusercontent.com/35412032/236375402-1c7f68da-ea3f-4c4a-ae28-7a7e7b22936b.png)
</details>  
<br>

> As for the translated strings from old file, which commands are you running? What is the output?

I runed `node toJson.js ./new ./old output.yaml`. You can got the file from previous reply. Then I got this - [output.zip](https://github.com/juvian/wc3-translate/files/11403037/output.zip).
Strings from old one are full translated, but they are all missing in the output file.

**Comment by juvian** [comment]
It is not wrong output, that is how yaml format works. That is not the correct way to keep translations from an old map. It should be `node toJson.js new_map old_map_translated old_map_untranslated output.yaml`

**Comment by Surgeol** [comment]
I'm sorry you are right, thanks for your help and made such a nice tool
