### ISSUE TITLE
unit or ability

### ISSUE THREAD

**Issue by null15** [juvian/wc3-translate#7]
There is no option for them on the web-interface?

**Comment by null15** [comment]
failed to parse war3map.w3a, will skip RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 2142268. Received 2142276

**Comment by null15** [comment]
[war3map.zip](https://github.com/juvian/wc3-translate/files/13910569/war3map.zip)

**Comment by juvian** [comment]
@null15 Those files are in file format 3 (reforged) and my tool uses a parsing library that does not support that. I was able to find the difference in other library and replicate it https://github.com/juvian/WC3MapTranslator/commit/0cc0d17113175bfdb56b3dc55b93e1679ab07e18

I have updated that in the website so it should work now, let me know

**Comment by null15** [comment]
> @null15 Those files are in file format 3 (reforged) and my tool uses a parsing library that does not support that. I was able to find the difference in other library and replicate it [juvian/WC3MapTranslator@0cc0d17](https://github.com/juvian/WC3MapTranslator/commit/0cc0d17113175bfdb56b3dc55b93e1679ab07e18)
> 
> I have updated that in the website so it should work now, let me know

I opened a dummy map with the war3map.w3a imported into it, but when I try to use it on the web interface, the only data I get back is: info, script and strings. Is it any of these?

**Comment by juvian** [comment]
@null15  Not sure what are you doing, it worked for me. Can you upload the dummy map and the data you get back?

**Comment by null15** [comment]
> @null15 Not sure what are you doing, it worked for me. Can you upload the dummy map and the data you get back?

Actually, this might sound strange but it worked this morning, I think I had to hard-reset the webpage, great work juvian. :)
